# Generated by Django 5.0.4 on 2024-06-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
